# Generated by Django 5.2 on 2025-04-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_customuser_location_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
