# Generated by Django 5.2 on 2025-05-05 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAidCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('importance_level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirstAidSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('step_number', models.IntegerField(default=1)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='user.firstaidcondition')),
            ],
        ),
    ]
