# Generated by Django 5.2 on 2025-05-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_firstaidcondition_healthtip_firstaidsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaidcondition',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='firstaidcondition',
            name='urgency_level',
            field=models.IntegerField(default=1),
        ),
    ]
