# Generated by Django 5.2 on 2025-05-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_ambulancebooking_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.CharField(default='Cooper Hospital', max_length=100),
        ),
    ]
