# Generated by Django 5.2 on 2025-05-07 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_appointment_hospital'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='firstaidcondition',
            table='user_firstaidcondition',
        ),
        migrations.AlterModelTable(
            name='healthtip',
            table='user_healthtip',
        ),
    ]
